Fix build on 32-bit arm platforms (#2376)
* IOUtils: fix build on 32-bit arm

Currently passenger fails to build on the Debian build daemons for
armhf/armel (i.e. ARM 32-bit systems) with the following error:

error: flexible array member ‘cmsghdr::__cmsg_data’ not at end of ‘struct Passenger::readFileDescriptor(int, long long unsigned int*)::<unnamed>

The `|| defined(__arm__)` seems to have been introduced by commit
312b5e1c65558e17cd30d1b28089078d8f614fbf as a fix for building on ARM in
the first place. This might be caused by compiler bugs at the time, and
can now be reverted.

* Fixes wrong type for mutex in regex v5

With the Boost.Regex to ehader-only library, the declaration
of a mutex that should have been changed from boost::static_mutex
to std::mutex was left behind. This was preventing regex from
being built for older arm platforms [1]

[1]: https://github.com/openwrt/packages/issues/15725

Signed-off-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>

----------------8<----------------8<----------------8<-----------------

This patch has been backported from the upstream boost repository.

Backported-by: Antonio Terceiro <asa@terceiro.xyz>
Origin: https://github.com/boostorg/regex/pull/132

Co-authored-by: Carlos Miguel Ferreira <carlosmf.pt@gmail.com>