Fix upstream_config.limit_rate initialization for Nginx 1.27.0 compatibility
seeing some regression build failure when building against nginx 1.27.0

```
/private/tmp/passenger-20240529-10206-38vspk/passenger-6.0.22/src/nginx_module/Configuration.c:228:42: error: incompatible integer to pointer conversion assigning to 'ngx_http_complex_value_t *' from 'size_t' (aka 'unsigned long') [-Wint-conversion]
2024-05-29T18:34:50.9320080Z         conf->upstream_config.limit_rate = NGX_CONF_UNSET_SIZE;
```

Signed-off-by: Rui Chen <rui@chenrui.dev>