IOUtils: fix build on 32-bit arm
Currently passenger fails to build on the Debian build daemons for
armhf/armel (i.e. ARM 32-bit systems) with the following error:

error: flexible array member ‘cmsghdr::__cmsg_data’ not at end of ‘struct Passenger::readFileDescriptor(int, long long unsigned int*)::<unnamed>

The `|| defined(__arm__)` seems to have been introduced by commit
312b5e1c65558e17cd30d1b28089078d8f614fbf as a fix for building on ARM in
the first place. This might be caused by compiler bugs at the time, and
can now be reverted.